name: CitasMedicas
options:
  bundleIdPrefix: com.medicare
  deploymentTarget:
    iOS: "16.0"
  createIntermediateGroups: true
  developmentLanguage: es

settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: "16.0"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    ENABLE_USER_SCRIPT_SANDBOXING: YES
    GENERATE_INFOPLIST_FILE: NO

targets:
  CitasMedicas:
    type: application
    platform: iOS
    sources:
      - path: CitasMedicas
        excludes:
          - "Resources/Info.plist"
    resources:
      - path: CitasMedicas/Assets.xcassets
      - path: CitasMedicas/Resources
      - path: CitasMedicas/Resources/es.lproj/Localizable.strings
      - path: CitasMedicas/Resources/en.lproj/Localizable.strings
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.medicare.citasmedicas
        INFOPLIST_FILE: CitasMedicas/Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MACCATALYST: NO
        SWIFT_EMIT_LOC_STRINGS: YES
    scheme:
      testTargets: []
